apiVersion: v1
kind: Service
metadata:
  name: node-blog
spec:
  selector:
    app: node-blog
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-blog
  template:
    metadata:
      labels:
        app: node-blog
    spec:
      serviceAccountName: eks-dynamodb-srv-acct
      containers:
        - name: node-blog
          image: kpatel55/node-blog:latest
          ports:
            - containerPort: 4000
